version: '3'

services:
  test_db_fastapi:
    image: postgres:15.1-alpine
    restart: always
    container_name: test_db_fastapi
    volumes:
      - test_reviro_psql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5

  test_web_fastapi:
    build: .
    container_name: test_web_fastapi
    command: sh -c "pytest -v"
    volumes:
      - .:/app
      - .:/tests
    ports:
      - 8008:8000
    env_file:
      - .env.test
    depends_on:
      test_db_fastapi:
        condition: service_healthy

volumes:
  test_reviro_psql_data:
