version: '3'

services:
  testDbFastapi:
    image: postgres:15.1-alpine
    restart: always
    container_name: testDbFastapi
    volumes:
      - test_reviro_psql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testReviroIntDb -U testReviroIntUser"]
      interval: 10s
      timeout: 10s
      retries: 5

  testWebFastapi:
    build: .
    container_name: testWebFastapi
    command: sh -c "pytest -v"
    volumes:
      - .:/app
      - .:/tests
    ports:
      - 8008:8000
    env_file:
      - .env.test
    depends_on:
      testDbFastapi:
        condition: service_healthy

volumes:
  test_reviro_psql_data:
